version: '3'
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    environment:
      CERTBOT_EMAIL: agarrett777@gmail.com
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    ports:
      - 80:80
      - 443:443

  web:
    build: frontend
    command: bash -c "npm run build && npm start"
    environment:
      API_URL: http://45.55.41.131:1337
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:3000"

    depends_on:
      - strapi

  strapi:
    image: strapi/strapi
    command: bash -c "yarn install --frozen-lockfile && yarn build && yarn start"
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      NODE_ENV: production
    networks:
      - strapi-app-network
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
  nginx_secrets:
