version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:dev
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=agarrett777@gmail.com
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-network
    restart: always

  web:
    build: frontend
    container_name: web
    command: bash -c "npm run build && npm start"
    environment:
      VIRTUAL_HOST: austingarrett.dev
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: austingarrett.dev
      LETSENCRYPT_EMAIL: agarrett777@gmail.com
      API_URL: https://austingarrett.dev/strapi
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    networks:
      - proxy-network
    restart: always

  strapi:
    image: strapi/strapi
    container_name: strapi
    command: bash -c "yarn install --frozen-lockfile && yarn build && yarn start"
    environment:
      VIRTUAL_HOST: austingarrett.dev
      LETSENCRYPT_HOST: austingarrett.dev
      VIRTUAL_PATH: /strapi/
      VIRTUAL_DEST: /
      LETSENCRYPT_EMAIL: agarrett777@gmail.com
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      NODE_ENV: production
    networks:
      - strapi-app-network
      - proxy-network
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"
    restart: always

networks:
  strapi-app-network:
    driver: bridge
  proxy-network:
    external:
      name: nginx-proxy

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  strapidata:
