version: '3'
services:
  web:
    build: frontend
    command: bash -c "npm run build && npm start"
    environment:
      API_URL: http://localhost:1337
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - strapi

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    networks:
      - strapi-app-network
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
